USE VISIONMUNDIAL

DECLARE @ID AS INT;
DECLARE @MUNICIPIO AS NVARCHAR(30);

DECLARE MUNI CURSOR FOR SELECT ID_Municipio, Municipio FROM MUNICIPIO

OPEN MUNI

FETCH NEXT FROM MUNI INTO
@ID,@MUNICIPIO

WHILE @@FETCH_STATUS = 0
BEGIN

UPDATE Municipio SET Municipio =RTRIM( @MUNICIPIO) where ID_Municipio = @ID

FETCH NEXT FROM MUNI INTO
@ID,@MUNICIPIO
END
CLOSE MUNI

DEALLOCATE MUNI


select * from Municipio
