
DECLARE @Table_Name NVARCHAR(100)

DECLARE MY_CURSOR CURSOR 
  LOCAL STATIC READ_ONLY FORWARD_ONLY
FOR 
SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_TYPE = 'BASE TABLE' 
AND TABLE_CATALOG='VISIONMUNDIAL' AND TABLE_NAME IN ('RolRecurso')

OPEN MY_CURSOR
FETCH NEXT FROM MY_CURSOR INTO @Table_Name
WHILE @@FETCH_STATUS = 0
BEGIN 
    
	DECLARE @query NVARCHAR(MAX) ;

	SET @query = N'UPDATE '+@Table_Name+ ' SET Agregar = 1, Modificar = 1, Eliminar = 1'

	--print @query;
	EXEC sp_executesql @query

	 
    FETCH NEXT FROM MY_CURSOR INTO @Table_Name
END
CLOSE MY_CURSOR
DEALLOCATE MY_CURSOR