
DECLARE @startDate DATETIME
DECLARE @endDate DATETIME
DECLARE @ID_Programa INT
DECLARE @step INT 

DECLARE MY_CURSOR CURSOR 
  LOCAL STATIC READ_ONLY FORWARD_ONLY
FOR 
SELECT FECHAINICIO, FECHAFINAL,ID_Programa FROM Programa

OPEN MY_CURSOR
FETCH NEXT FROM MY_CURSOR INTO @startDate,@endDate,@ID_Programa
SET @step = 0;
WHILE @@FETCH_STATUS = 0
BEGIN 

	DECLARE @startDateINSERT DATETIME
	DECLARE @endDateINSERT DATETIME
	DECLARE MY_CURSORINSERT CURSOR 
	LOCAL STATIC READ_ONLY FORWARD_ONLY
	FOR 
	SELECT DATEADD(DAY,-(DATEPART(DW,DATEADD(WEEK, x.number, @StartDate))-2),DATEADD(WEEK, x.number, @StartDate)) as [StartDate]
				,DATEADD(DAY,-(DATEPART(DW,DATEADD(WEEK, x.number + 1, @StartDate))-1) ,DATEADD(WEEK, x.number + 1, @StartDate)) AS [EndDate]
				FROM master.dbo.spt_values x
				WHERE x.type = 'P' AND x.number <= DATEDIFF(WEEK, @StartDate, DATEADD(WEEK,0,CAST(@EndDate AS DATE)))

	OPEN MY_CURSORINSERT
	FETCH NEXT FROM MY_CURSORINSERT INTO @startDateINSERT,@endDateINSERT
	SET @step = 0;
	WHILE @@FETCH_STATUS = 0
	BEGIN 

		INSERT INTO Actividad(Codigo,ActividadDescripcion,Estado,ID_Programa,Observacion,Fecha) VALUES ('ACT-TEMPLATE','','A',@ID_Programa,'',@startDateINSERT)

	 FETCH NEXT FROM MY_CURSORINSERT INTO @startDateINSERT,@endDateINSERT
	END
	CLOSE MY_CURSORINSERT
	DEALLOCATE MY_CURSORINSERT

    FETCH NEXT FROM MY_CURSOR INTO @startDate,@endDate,@ID_Programa
END
CLOSE MY_CURSOR
DEALLOCATE MY_CURSOR