//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Actividad
    {
        public int ID_Actividad { get; set; }
        public string Codigo { get; set; }
        public string ActividadDescripcion { get; set; }
        public string Estado { get; set; }
        public int ID_Programa { get; set; }
        public string Observacion { get; set; }
        public System.DateTime Fecha { get; set; }
    
        public virtual Programa Programa { get; set; }
    }
}
