//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class AsignacionRecursoHumano
    {
        public AsignacionRecursoHumano()
        {
            this.CreadoPor = "";
            this.ModificadoPor = "";
            this.FechaCreacion = new DateTime(1990, 1, 1);
            this.FechaModificacion = new DateTime(1990, 1, 1);
        }
        public int ID_AsignacionRecursoHumano { get; set; }
        public int ID_Puesto { get; set; }
        public int ID_Persona { get; set; }
        public int ID_Proyecto { get; set; }
        public string CreadoPor { get; set; }
        public Nullable<System.DateTime> FechaCreacion { get; set; }
        public string ModificadoPor { get; set; }
        public Nullable<System.DateTime> FechaModificacion { get; set; }
    
        public virtual Persona Persona { get; set; }
        public virtual Proyecto Proyecto { get; set; }
        public virtual Puesto Puesto { get; set; }
    }
}
