//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class AsignacionRecursoHumano
    {
        public int ID_AsignacionRecursoHumano { get; set; }
        public int ID_Puesto { get; set; }
        public int ID_Persona { get; set; }
        public int ID_Proyecto { get; set; }
    
        public virtual Persona Persona { get; set; }
        public virtual Proyecto Proyecto { get; set; }
        public virtual Puesto Puesto { get; set; }
    }
}
