//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Beneficiario
    {
        public Beneficiario()
        {
            this.BeneficiarioAdicional = new HashSet<BeneficiarioAdicional>();
            this.BeneficiarioCompromiso = new HashSet<BeneficiarioCompromiso>();
            this.BeneficiarioEducacion = new HashSet<BeneficiarioEducacion>();
            this.BeneficiarioSalud = new HashSet<BeneficiarioSalud>();
            this.Asistencia = new HashSet<Asistencia>();
            this.AsignacionMateria = new HashSet<AsignacionMateria>();
            this.CreadoPor = "";
            this.ModificadoPor = "";
            this.FechaCreacion = new DateTime(1990, 1, 1);
            this.FechaModificacion = new DateTime(1990, 1, 1);
        }
    
        public int ID_Beneficiario { get; set; }
        public string Nombre { get; set; }
        public string Apellido { get; set; }
        public string Dui { get; set; }
        public string Codigo { get; set; }
        public string Edad { get; set; }
        public string Sexo { get; set; }
        public string Direccion { get; set; }
        public int ID_Programa { get; set; }
        public string CreadoPor { get; set; }
        public Nullable<System.DateTime> FechaCreacion { get; set; }
        public string ModificadoPor { get; set; }
        public Nullable<System.DateTime> FechaModificacion { get; set; }
    
        public virtual Programa Programa { get; set; }
        public virtual ICollection<BeneficiarioAdicional> BeneficiarioAdicional { get; set; }
        public virtual ICollection<BeneficiarioCompromiso> BeneficiarioCompromiso { get; set; }
        public virtual ICollection<BeneficiarioEducacion> BeneficiarioEducacion { get; set; }
        public virtual ICollection<BeneficiarioSalud> BeneficiarioSalud { get; set; }
        public virtual ICollection<Asistencia> Asistencia { get; set; }
        public virtual ICollection<AsignacionMateria> AsignacionMateria { get; set; }
    }
}
