//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class BitacoraDetalle
    {
        public int ID_BitacoraDetalle { get; set; }
        public int ID_Bitacora { get; set; }
        public string Actividad { get; set; }
        public string Observaciones { get; set; }
    
        public virtual Bitacora Bitacora { get; set; }
    }
}
