//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Comunidad
    {
        public Comunidad()
        {
            this.Programa = new HashSet<Programa>();
        }
    
        public int ID_Comunidad { get; set; }
        public string Comunidad1 { get; set; }
        public int ID_Municipio { get; set; }
    
        public virtual Municipio Municipio { get; set; }
        public virtual ICollection<Programa> Programa { get; set; }
    }
}
