//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Examen
    {
        public Examen()
        {
            this.ExamenResultado = new HashSet<ExamenResultado>();
        }
    
        public int ID_Examen { get; set; }
        public int ID_Materia { get; set; }
        public string NumeroExamen { get; set; }
        public string Archivo { get; set; }
    
        public virtual Materia Materia { get; set; }
        public virtual ICollection<ExamenResultado> ExamenResultado { get; set; }
    }
}
