//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Objetivo
    {
        public int ID_Objetivo { get; set; }
        public string Objetivo1 { get; set; }
        public string ObjetivoDescripcion { get; set; }
        public string TipoObjetivo { get; set; }
        public int ID_Programa { get; set; }
    
        public virtual Programa Programa { get; set; }
    }
}
