//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class PlanSemanal
    {
        public PlanSemanal()
        {
            this.PlanSemanalDetalle = new HashSet<PlanSemanalDetalle>();
        }
    
        public int ID_PlanSemanal { get; set; }
        public int ID_Persona { get; set; }
        public System.DateTime FechaInicio { get; set; }
        public System.DateTime FechaFinal { get; set; }
    
        public virtual Persona Persona { get; set; }
        public virtual ICollection<PlanSemanalDetalle> PlanSemanalDetalle { get; set; }
    }
}
