//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Programa
    {
        public Programa()
        {
            this.Indicador = new HashSet<Indicador>();
            this.Objetivo = new HashSet<Objetivo>();
            this.Beneficiario = new HashSet<Beneficiario>();
            this.Actividad = new HashSet<Actividad>();
            this.CreadoPor = "";
            this.ModificadoPor = "";
            this.FechaCreacion = new DateTime(1990, 1, 1);
            this.FechaModificacion = new DateTime(1990, 1, 1);
        }
    
        public int ID_Programa { get; set; }
        public string Codigo { get; set; }
        public string ProgramaDescripcion { get; set; }
        public string Estado { get; set; }
        public System.DateTime FechaInicio { get; set; }
        public System.DateTime FechaFinal { get; set; }
        public int ID_Proyecto { get; set; }
        public int ID_TipoPrograma { get; set; }
        public int ID_Comunidad { get; set; }
        public string CreadoPor { get; set; }
        public Nullable<System.DateTime> FechaCreacion { get; set; }
        public string ModificadoPor { get; set; }
        public Nullable<System.DateTime> FechaModificacion { get; set; }
    
        public virtual Comunidad Comunidad { get; set; }
        public virtual ICollection<Indicador> Indicador { get; set; }
        public virtual ICollection<Objetivo> Objetivo { get; set; }
        public virtual Proyecto Proyecto { get; set; }
        public virtual TipoPrograma TipoPrograma { get; set; }
        public virtual ICollection<Beneficiario> Beneficiario { get; set; }
        public virtual ICollection<Actividad> Actividad { get; set; }
    }
}
