//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Proyecto
    {
        public Proyecto()
        {
            this.AsignacionRecursoHumano = new HashSet<AsignacionRecursoHumano>();
            this.Programa = new HashSet<Programa>();
        }
    
        public int ID_Proyecto { get; set; }
        public string Codigo { get; set; }
        public string ProyectoDescripcion { get; set; }
        public string Estado { get; set; }
    
        public virtual ICollection<AsignacionRecursoHumano> AsignacionRecursoHumano { get; set; }
        public virtual ICollection<Programa> Programa { get; set; }
    }
}
