//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Puesto
    {
        public int ID_Puesto { get; set; }
        public string Puesto1 { get; set; }
        public string PuestoDescripcion { get; set; }
        public int ID_TipoPuesto { get; set; }
    
        public virtual TipoPuesto TipoPuesto { get; set; }
    }
}
