//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Recurso
    {
        public Recurso()
        {
            this.RolRecurso = new HashSet<RolRecurso>();
        }
    
        public int ID_Recurso { get; set; }
        public string Recurso1 { get; set; }
        public string Pagina { get; set; }
    
        public virtual ICollection<RolRecurso> RolRecurso { get; set; }
    }
}
