//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class RolRecurso
    {
        public int ID_RolRecurso { get; set; }
        public int ID_Rol { get; set; }
        public int ID_Recurso { get; set; }
    
        public virtual Recurso Recurso { get; set; }
        public virtual Rol Rol { get; set; }
    }
}
