//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class RolRecurso
    {
        public RolRecurso()
        {
            this.CreadoPor = "";
            this.ModificadoPor = "";
            this.FechaCreacion = new DateTime(1990, 1, 1);
            this.FechaModificacion = new DateTime(1990, 1, 1);
            this.Agregar = true;
            this.Modificar = true;
            this.Eliminar = true;
        }
        public int ID_RolRecurso { get; set; }
        public int ID_Rol { get; set; }
        public int ID_Recurso { get; set; }
        public string CreadoPor { get; set; }
        public Nullable<System.DateTime> FechaCreacion { get; set; }
        public string ModificadoPor { get; set; }
        public Nullable<System.DateTime> FechaModificacion { get; set; }
        public Nullable<bool> Agregar { get; set; }
        public Nullable<bool> Modificar { get; set; }
        public Nullable<bool> Eliminar { get; set; }
    
        public virtual Recurso Recurso { get; set; }
        public virtual Rol Rol { get; set; }
    }
}
