//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class TipoPuesto
    {
        public TipoPuesto()
        {
            this.Puesto = new HashSet<Puesto>();
        }
    
        public int ID_TipoPuesto { get; set; }
        public string TipoPuesto1 { get; set; }
        public string TipoPuestoDescripcion { get; set; }
    
        public virtual ICollection<Puesto> Puesto { get; set; }
    }
}
