//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class VISIONMUNDIALEntities : DbContext
    {
        public VISIONMUNDIALEntities()
            : base("name=VISIONMUNDIALEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Usuario> Usuario { get; set; }
        public DbSet<Recurso> Recurso { get; set; }
        public DbSet<Rol> Rol { get; set; }
        public DbSet<RolRecurso> RolRecurso { get; set; }
        public DbSet<UsuarioRol> UsuarioRol { get; set; }
    }
}
