//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class VISIONMUNDIALEntities : DbContext
    {
        public VISIONMUNDIALEntities()
            : base("name=VISIONMUNDIALEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Usuario> Usuario { get; set; }
        public DbSet<Recurso> Recurso { get; set; }
        public DbSet<Rol> Rol { get; set; }
        public DbSet<RolRecurso> RolRecurso { get; set; }
        public DbSet<UsuarioRol> UsuarioRol { get; set; }
        public DbSet<Indicador> Indicador { get; set; }
        public DbSet<Objetivo> Objetivo { get; set; }
        public DbSet<TipoPrograma> TipoPrograma { get; set; }
        public DbSet<Comunidad> Comunidad { get; set; }
        public DbSet<Departamento> Departamento { get; set; }
        public DbSet<Municipio> Municipio { get; set; }
        public DbSet<Puesto> Puesto { get; set; }
        public DbSet<TipoPuesto> TipoPuesto { get; set; }
        public DbSet<Bitacora> Bitacora { get; set; }
        public DbSet<BitacoraDetalle> BitacoraDetalle { get; set; }
        public DbSet<Persona> Persona { get; set; }
        public DbSet<PlanSemanal> PlanSemanal { get; set; }
        public DbSet<PlanSemanalDetalle> PlanSemanalDetalle { get; set; }
        public DbSet<Proyecto> Proyecto { get; set; }
        public DbSet<AsignacionRecursoHumano> AsignacionRecursoHumano { get; set; }
        public DbSet<Programa> Programa { get; set; }
        public DbSet<Beneficiario> Beneficiario { get; set; }
        public DbSet<BeneficiarioAdicional> BeneficiarioAdicional { get; set; }
        public DbSet<BeneficiarioCompromiso> BeneficiarioCompromiso { get; set; }
        public DbSet<BeneficiarioEducacion> BeneficiarioEducacion { get; set; }
        public DbSet<BeneficiarioSalud> BeneficiarioSalud { get; set; }
        public DbSet<Actividad> Actividad { get; set; }
        public DbSet<Asistencia> Asistencia { get; set; }
        public DbSet<AsignacionMateria> AsignacionMateria { get; set; }
        public DbSet<Examen> Examen { get; set; }
        public DbSet<ExamenResultado> ExamenResultado { get; set; }
        public DbSet<Materia> Materia { get; set; }
        public DbSet<sysdiagrams> sysdiagrams { get; set; }
    }
}
